version: '2'
services:
  app-api:
    container_name: api
    depends_on:
      - 'postgres'
      - 'redis'
    build:
        context: .
        args:
          - SITE_SUFFIX=${SITE_SUFFIX}
          - SECRET_KEY_BASE=${SECRET_KEY_BASE}
          - API_SCHEME=${API_SCHEME}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - SITE_SUFFIX=${SITE_SUFFIX}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
    volumes:
      - app_public:/var/www/app/public
    expose:
      - "3000"

  app-frontend:
    container_name: frontend
    build:
        context: docker/experiment-frontend
        args:
          - API_URL=${API_URL}
          - API_SCHEME=${API_SCHEME}
          - ELICIT_LANDING_URL=${ELICIT_URL}\/participant
    volumes:
      - 'fe_public:/var/www/frontend/public'

  web:
    container_name: web
    build:
        context: docker/revproxy
        args:
          - API_SCHEME=${API_SCHEME}
          - SITE_SUFFIX=${SITE_SUFFIX}
    volumes:
      - 'app_public:/var/www/app/public'
      - 'fe_public:/var/www/frontend/public'
      - ./certs:/certs
    links:
      - app-api
    ports:
      - "80:8080"
      - "443:8443"
      - "8080:8081"

  redis:
    container_name: redis
    image: 'redis:3.2-alpine'
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/data'

  postgres:
    container_name: postgres
    image: 'postgres:9.6-alpine'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

volumes:
  redis:
  postgres:
  certs:
  fe_public:
  app_public:
