version: '2'
services:
  app-api:
    container_name: api
    depends_on:
      - 'postgres15'
      - 'redis'
    build:
        context: .
        args:
          - SITE_SUFFIX=${SITE_SUFFIX}
          - SECRET_KEY_BASE=${SECRET_KEY_BASE}
          - API_SCHEME=${EXTERNAL_API_SCHEME}
          - WEB_CLIENT_SECRET=${WEB_CLIENT_SECRET}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - SITE_SUFFIX=${SITE_SUFFIX}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - WEB_CLIENT_SECRET=${WEB_CLIENT_SECRET}
      - NEWRELIC_LICENSE_KEY=${NEWRELIC_LICENSE_KEY}
    volumes:
      - app_public:/var/www/app/public
    expose:
      - "3000"
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  app-frontend:
    container_name: frontend
    build:
        context: docker/experiment-frontend
        args:
          - API_URL=${API_URL}
          - API_SCHEME=${EXTERNAL_API_SCHEME}
          - ELICIT_LANDING_URL=${ELICIT_URL}\/participant
    volumes:
      - 'fe_public:/var/www/frontend/public'
    logging:
      options:
        max-size: "10m"
        max-file: "2"

  web:
    container_name: web
    build:
        context: docker/revproxy
        args:
          - API_SCHEME=${API_SCHEME}
          - SITE_SUFFIX=${SITE_SUFFIX}
          - ENABLED_MODULES=brotli
    volumes:
      - 'app_public:/var/www/app/public'
      - 'fe_public:/var/www/frontend/public'
      - ./certs:/certs
    links:
      - app-api
    ports:
      - "80:8080"
      - "443:8443"
      - "8080:8081"
    logging:
      options:
        max-size: "10m"
        max-file: "2"

  redis:
    container_name: redis
    image: 'redis:7-alpine'
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - '6379:6379'
    volumes:
      - redis:/data
    logging:
      options:
        max-size: "10m"
        max-file: "2"

  postgres15:
    container_name: postgres15
    image: 'postgres:15.2-alpine'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - 'postgres15:/var/lib/postgresql/data'
      - 'postgres:/var/lib/postgresql/olddata:ro'
      - 'postgres15-backups:/var/lib/postgresql/backups'
    logging:
      options:
        max-size: "10m"
        max-file: "2"

volumes:
  redis:
  postgres:
  postgres15:
  postgres15-backups:
  certs:
  fe_public:
  app_public:
