default: &default
  participant_frontend:   
    host: localhost
    port: 5504
    scheme: http
  elicit_portal:
    host: localhost
    port: 3000
    scheme: http

development:
  <<: *default

test:
  <<: *default

prod_env: &prod_env
  participant_frontend:   
    host: experiment-elicit.<%= ENV['SITE_SUFFIX'] %>
    port: 443
    scheme: https
  elicit_portal:
    host: elicit.<%= ENV['SITE_SUFFIX'] %>
    port: 443
    scheme: https


local_env: &local_env
  participant_frontend:   
    host: docker.local
    port: 8080
  elicit_portal:
    host: docker.local
    port: 80

production:
  <<: *prod_env
