default: &default
  participant_frontend:
    host: localhost
    port: 5504
    scheme: http
  elicit_portal:
    host: localhost
    port: 3000
    scheme: http

development:
  <<: *default

test:
  <<: *default

prod_env: &prod_env
  participant_frontend:
    host: experiment-elicit.<%= ENV['SITE_SUFFIX'] %>
    port:  <% ENV['API_SCHEME'] == 'https' ? 443 : 80 %>
    scheme: <% ENV['API_SCHEME'] %>
  elicit_portal:
    host: elicit.<%= ENV['SITE_SUFFIX'] %>
    port: <%= ENV['API_SCHEME'] == 'https' ? 443 : 80 %>
    scheme: <%= ENV['API_SCHEME'] %>

local_env: &local_env
  participant_frontend:
    host: experiment-elicit.<%= ENV['SITE_SUFFIX'] %>
    port: <%= ENV['API_SCHEME'] == 'https' ? 443 : 80 %>
    scheme: <%= ENV['API_SCHEME'] %>
  elicit_portal:
    host: elicit.<%= ENV['SITE_SUFFIX'] %>
    port: <%= ENV['API_SCHEME'] == 'https' ? 443 : 80 %>
    scheme: <%= ENV['API_SCHEME'] %>

production:
  <<: *<%= (ENV.fetch('SITE_SUFFIX') { 'docker.local' }) == 'compute.dtu.dk' ? 'prod_env' : 'local_env' %>
