default: &default
  participant_frontend:   
    host: localhost
    port: 5504
  elicit_portal:   
    host: localhost
    port: 3000

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
